name: GalaxyBoxPvP
version: '${version}'
main: xyz.lncvrt.galaxyboxpvp.GalaxyBoxPvP
api-version: '1.21'
depend:
  - PlaceholderAPI
  - Essentials
  - WorldEdit
  - WorldGuard
  - BetterTeams
commands:
  autocompress:
    description: Auto compressor
    usage: /autocompress
  sky:
    description: Teleports you to sky world
    usage: /sky