name: LncvrtBox
version: '${version}'
main: io.github.lncvrt.lncvrtbox.LncvrtBox
api-version: '1.20'
depend:
  - PlaceholderAPI
  - Essentials
  - WorldEdit
  - WorldGuard
  - Geyser-Spigot
  - floodgate
commands:
  autocompress:
    description: Auto compressor
    usage: /autocompress
  clearchat:
    description: Clears chat
    usage: /clearchat
    aliases:
      - cc
    permission: lncvrtbox.clearchat
  fix:
    description: fix
    permission: lncvrtbox.admin
    usage: /fix
  link:
    description: Links your discord
    usage: /link
  lockchat:
    description: Lockchat
    usage: /lockchat
  ping:
    description: Shows your ping
    usage: /ping [player]
  rules:
    description: Rules
    usage: /rules
  sky:
    description: Teleports you to sky world
    usage: /sky
  unlink:
    description: Unlinks your discord
    usage: /unlink