name: LncvrtBox
version: '${version}'
main: io.github.lncvrt.lncvrtbox.LncvrtBox
api-version: '1.20'
depend:
  - PlaceholderAPI
  - LuckPerms
  - Essentials
commands:
  settag:
    description: Command has been removed
    usage: /settag
  sky:
    description: Teleports you to sky world
    usage: /sky
  clearchat:
    description: Clears chat
    usage: /clearchat
    aliases:
      - cc
    permission: lncvrtbox.clearchat
  link:
    description: Links your discord
    usage: /link
  unlink:
    description: Unlinks your discord
    usage: /unlink
  autocompress:
    description: Auto compressor
    usage: /autocompress
  rules:
    description: Rules
    usage: /rules
  lockchat:
    description: Lockchat
    usage: /lockchat